### ISSUE TITLE
Support multiple distinct open pages

### ISSUE THREAD

**Issue by EricForgy** [EricForgy/JavaScriptBridge.jl#5]
Current implement broadcasts to all open windows uniformly and simultaneously.

**Comment by RoyiAvital** [comment]
Hello,

There is a JaveScript Function I want to implement in Julia.

For my unit test I want to send same inputs (In this case an image + array of numbers) to both functions and compare their result.

Will I be able to tackle this scenario with your package?

Thank You.

**Comment by EricForgy** [comment]
Have a look at Pages.jl. I am not maintaining this package anymore, but started working on Pages.jl again recently.

**Comment by EricForgy** [comment]
This is resolved in Pages.jl.
